name: travy

services:

  posts_service:
    build:
      context: ./services/posts_service
    container_name: posts_service
    ports:
      - "3000:3000"
    networks:
      - travynet

  transport_service:
    build:
      context: ./services/transport_service
    container_name: transport_service
    env_file:
      - .env
    ports:
      - "3001:3001"
    networks:
      - travynet

  auth_service:
    build:
      context: ./services/auth_service
    container_name: auth_service
    ports:
      - "5002:5002"
    networks:
      - travynet

  contact_service:
    build:
      context: ./services/contact_service
    container_name: contact_service
    ports:
      - "3007:3007"
    networks:
      - travynet

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - posts_service
      - transport_service
      - auth_service
      - contact_service
    ports:
      - "8080:80"
    networks:
      - travynet

networks:
  travynet:
    driver: bridge
