# This is a docker compose file for defining and running
# multi-container environments. It simplifies the control
# of your application stack into a single configuration
# file. The following commands are useful:
#
#   docker compose up          - "runs" the entire system
#   docker compose up --build  - force a build and "runs" system
#   docker compose up -d       - "runs" system in detacted mode
#   docker compose down        - "closes" the entire system and deletes everything
#   docker compose stop        - stop running containers without removing them
#   docker compose start       - start previously stopped containers

name: travy

services:

  posts_service:
    build:
      context: ./posts_service
    container_name: posts_service
    ports:
      - "3000:3000"
    networks:
      - travynet

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - posts_service
    ports:
      - "8080:80"
    networks:
      - travynet

networks:
  travynet:
    driver: bridge

